[phases.setup]
nixPkgs = ["nodejs_22", "python312", "python312Packages.gdal"]

[phases.install]
cmds = ["pnpm install"]

[phases.build]
cmds = ["cd packages/mcp-gdal && npx tsc --outDir dist --esModuleInterop --module nodenext --target es2022 --moduleResolution nodenext --skipLibCheck src/index.ts"]

[start]
cmd = "node packages/mcp-gdal/dist/index.js"
